# 👋 Welcome to Week 2 Day 1 of Python and AI Bootcamp

👩‍🏫 **Trainer:** Muhammad Aqib Javed  

🤖 **Software Engineer** from UET Taxila  

🔗 **LinkedIn:** [linkedin.com/in/Aqib_Niazi](https://www.linkedin.com/in/maqibjaved/)  
💻 **GitHub:** [github.com/AqibNiazi](https://github.com/AqibNiazi)


# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

**Why Use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to **50x faster** than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

**Why is NumPy Faster Than Lists?**

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

**Which Language is NumPy written in?**

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

**Installation of NumPy**

If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:

C:\Users\Your Name>pip install numpy

**Import NumPy**

Once NumPy is installed, import it in your applications by adding the import keyword:

`import numpy`

Now NumPy is imported and ready to use.

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**NumPy as np**

NumPy is usually imported under the np alias.

**alias:** In Python alias are an alternate name for referring to the same thing.

Create an alias with the **as** keyword while importing:

In [ ]:
import numpy as np

Now the NumPy package can be referred to as np instead of numpy.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# NumPy Creating Arrays

**Create a NumPy ndarray Object**

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**type():** This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is **numpy.ndarray** type.

To create an ndarray, we can pass a list, tuple or any array-like object into the **array()** method, and it will be converted into an ndarray:

In [ ]:
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


**Dimensions in Arrays**

A dimension in arrays is one level of array depth (nested arrays).

**nested array:** are arrays that have arrays as their elements.

**0-D Arrays**

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
import numpy as np

arr = np.array(42)

print(arr)

42


**1-D Arrays**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**2-D Arrays**

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


**3-D arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Check Number of Dimensions?**

NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


**NumPy Array Indexing**

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


**Access 2-D Arrays**

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
# Access the element on the first row, second column:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 0th row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
# Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


**Access 3-D Arrays**

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
# Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


**Negative Indexing**

Use negative indexing to access an array from the end.



In [ ]:
# Print the last element from the 2nd dim:

import numpy as np

arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
    ])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


**NumPy Array Slicing**

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: **[start:end]**.

We can also define the step, like this: **[start:end:step]**.

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
# Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


**Note:** The result includes the start index, but **excludes** the **end index**.

In [ ]:
# Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
# Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


**Negative Slicing**

Use the minus operator to refer to an index from the end:

In [ ]:
# Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


**STEP**

Use the **step** value to determine the step of the slicing:

In [ ]:
# Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
# Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


**Slicing 2-D Arrays**

In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np
# arr[row_start:row_end, column_start:column_end]
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
# From both elements, return index 2:

import numpy as np
# arr[row_start:row_end, column_start:column_end]
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
    ])

print(arr[0:2, 2])

[3 8]


In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# arr[row_start:row_end, column_start:column_end]
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types
**Data Types in Python**

By default Python have these data types:

**strings** - used to represent text data, the text is given under quote marks. e.g. "ABCD"

**integer** - used to represent integer numbers. e.g. -1, -2, -3

**float** - used to represent real numbers. e.g. 1.2, 42.42

**boolean** - used to represent True or False.

**complex** - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

**Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.



*   i - integer
*   b - boolean
*   u - unsigned integer
*   f - float
*   c - complex float
*   m - timedelta
*   M - datetime
*   O - object
*   S - string
*   U - unicode string
*   V - fixed chunk of memory for other type ( void )

**Checking the Data Type of an Array**

The NumPy array object has a property called **dtype** that returns the data type of the array:

In [ ]:
# Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
# Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


**Creating Arrays With a Defined Data Type**

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [ ]:
# Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


**What if a Value Can Not Be Converted?**

If a type is given in which elements can't be casted then NumPy will raise a **ValueError**.

**ValueError**: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [ ]:
# A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

**Converting Data Type on Existing Arrays**

The best way to change the data type of an existing array, is to make a copy of the array with the **astype()** method.

The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
# Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


**Shape of an Array**

The shape of an array is the number of elements in each dimension.

**Get the Shape of an Array**

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

**Reshaping arrays**

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can **add** or **remove** dimensions or change number of elements in each dimension.

In [ ]:
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Can We Reshape Into any Shape?**

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [ ]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

**Iterating Arrays**

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
# Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

In [ ]:
# Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

In [ ]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3])               # From Python list
arr2 =np.zeros((2, 3))                  # 2x3 array of zeros
arr3 =np.ones((3, 3))                   # 3x3 array of ones

# np.arange() creates a NumPy array with evenly spaced values within a specified range.
# np.arange(start, stop, step)
arr4 =np.arange(0, 11, 2)               # From 0 to 10 step 2
arr5 =np.linspace(0, 1, 5)              # 5 evenly spaced numbers between 0 and 1

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

In [ ]:
# Mathematical operations
a = np.array([[1, 2, 3],[1,2,3]])
b = np.array([[4, 5, 6],[4, 5, 6]])

print(a + b)     # Addition
print(a - b)     # Subtraction

# a = np.array([[1, 2, 3],
#               [4, 5, 6]])     # shape (2, 3)

# b = np.array([[7, 8],
#               [9, 10],
#               [11, 12]])       # shape (3, 2)

# result = np.dot(a, b)
# print("Matrix Multiplication:\n", result)

# Random numbers
print(np.random.rand(2, 5))

**Pandas Lecture Link**

[Colab_File](https://colab.research.google.com/drive/1F39MhYrHJtRsCvoen36nvBaARGC_s-b0?usp=sharing)